Add option for AMGX build.
neams-th-coe/cardinal pull request #576
Opened 2023-02-08 21:39 UTC by aprilnovak

Adds a Makefile variable to easily turn on the AMGX in Cardinal.

2023-02-08 22:04 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/1340554/) on 27d4102 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/cardinal/docs/PRs/576/site)

This comment will be updated on new commits.

2023-02-08 22:24 UTC, jma6166 requested changes
In the makefile if we are using amgx we should enable cuda since it is only applicable on nvidia gpus. Also, we should enable amgx even with denable flag.

2023-02-08 22:30 UTC, aprilnovak commented
Can you clarify what you mean by this?

> Also, we should enable amgx even with denable flag.

2023-02-08 23:37 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1340744/) on fc19442 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/cardinal/docs/PRs/576/coverage)



This comment will be updated on new commits.

2023-07-08 00:25 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1640998/) on ba1d537 wanted to post the following:


The following coverage requirement(s) failed:
- Coverage rate 88.62% is less than the required 85.0%

2023-07-08 00:34 UTC, merged